version: '3.3'

services:
  # db:
  #   image: postgres:14.2-alpine
  #   environment:
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #   volumes:
  #     - database:/var/lib/postgresql/data
  #   restart: always
  # websockets:
  #   image: jazz_chords/websockets:latest
  #   build: ./websockets
  #   ports:
  #     - "7002:80"
  # backend:
  #   image: jazz_chords/backend:latest
  #   build: ./backend
  #   volumes:
  #     - ./backend/src:/app/src
  #   ports:
  #     - "7001:80"
  #   depends_on:
  #     - db
  #     - websockets
  #   restart: always
  frontend:
    image: jazz_chords/frontend:latest
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    restart: always
  nginx:
    image: jazz_chords/nginx:latest
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    ports:
      - "12432:80"
    depends_on:
      # - backend
      - frontend
      # - websockets
    restart: always
  # cron:
  #   image: jazz_chords/cron:latest
  #   build: ./cron
  #   depends_on:
  #     - nginx
  #   restart: always


volumes:
  database:
