# Generated by Django 4.0.4 on 2022-06-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_wordlist_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='daily_set_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
